### PR TITLE
Issues with session.delete

### PR DESCRIPTION
**Pull request by DavideD**
I was trying session.delete(String, Object)  but it doesn't seem to work. Am I doing something wrong or is it a bug?

1. Doesn't recognize the entity name defined using `@Entity`
2. Cannot access the `@Id` field

### CODE REVIEW

**Comment by yrodiere** [comment]
> Doesn't recognize the entity name defined using @Entity

@DavideD You need to use the Hibernate native entity name. It's not necessarily the same as the JPA entity name. Usually it's not the same: the Hibernate native entity name is the FQCN, while the JPA entity name is either what you set in `@Entity(name = ...)` or (by default) the simple class name.

> Cannot access the @Id field

That indeed looks like a bug. It rings a bell, but I can't find where I read about this...

**Comment by yrodiere** [comment]
> @DavideD You need to use the Hibernate native entity name. It's not necessarily the same as the JPA entity name. Usually it's not the same: the Hibernate native entity name is the FQCN, while the JPA entity name is either what you set in `@Entity(name = ...)` or (by default) the simple class name.

See also https://github.com/hibernate/hibernate-orm/blob/1d67993173b6300c8c5f70d159f76d8958fd6b2f/hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java#L247-L249

**Comment by DavideD** [comment]
> You need to use the Hibernate native entity name

Sure, that's what I did to make it work in the second test. But is it by design?

**Comment by dreab8** [comment]
About `Session#delete(String entityName, Object object)` the object is the instance to be removed not its id.

**Comment by yrodiere** [comment]
> Sure, that's what I did to make it work in the second test. But is it by design?

As far as I know, it's been that way for years, and probably from the inception of Hibernate ORM. The delete method accepting an entity name is not part of JPA.

**Comment by DavideD** [comment]
You are right @dreab8. I should have read the javadoc better. I got confused becacause in reactive we have a similar method that actually uses the id.

> The delete method accepting an entity name is not part of JPA, so it kind of makes sense.

I would expect changing the entity name to work for all methods. But  I haven't read all the docs in details and I don't mind enough either way.

**Comment by sebersole** [comment]
> > The delete method accepting an entity name is not part of JPA, so it kind of makes sense.
> 
> I would expect changing the entity name to work for all methods. But I haven't read all the docs in details and I don't mind enough either way.

That's the thing though... there are 3 "entity names", depending on context.  We did not go back and retrofit the JPA notions of an entity name into legacy Hibernate APIs.  Should we have?  :shrug:

**Comment by DavideD** [comment]
I don't know.

Isn't that the only way to specify an alternative name for the entity? As a user that doesn't know all the implementation history and details, why would you expect it to be different in this case?

Also, in this particular case, isn't the entity name always the `Class.getName()`?
Why not change the javadoc and say that we need the class name instead of the entity name?

**Comment by DavideD** [comment]
When I say "in this particular case" I mean when using `session.delete`.

**Comment by DavideD** [comment]
> 3 "entity names

3? I'm aware of the full-path and the one define with `@Entity. Which one is the 3rd one?`

**Comment by sebersole** [comment]
> 3? I'm aware of the full-path and the one define with @Entity. Which one is the 3rd one?

Just look in `PersistentClass` -

* className
* entityName
* jpaEntityName

`entityName` is the thing Hibernate uses internally.  It will be either the FQN or a name specified in `hbm.xml` (de-typed models).  It is also the thing that Hibernate expects when using the APIs that accept an entity-name.  

In fact, anytime you see Hibernate accepting a String as the "entity name" on an API it will be this `entityName`, never the "JPA entity name".  In fact, JPA does not even expose **any** APIs which allow you to use its entity-name - that's because JPA does not support de-typed models and so it **always** expects a Class reference.


> Isn't that the only way to specify an alternative name for the entity? As a user that doesn't know all the implementation history and details, why should I expect it to be different in this case?

No idea how this is "implementation history".  Aside from use in HQL, JPA simply and totally does not support referring to the entity type by name.


> Also, [when using session.delete], isn't the entity name always the `Class.getName()`? Why not change the javadoc and say that we need the class name instead of the entity name?

Because it's not.  In fact, I wonder if you are actually using the wrong form for your purpose.  How come you use `#delete(String,Object)` as opposed to `#delete(Object)`?

**Comment by DavideD** [comment]
Ah, ok, so if I understand correclty, the entity name (define using `@Entity(name = ...)`) only works when using HQL. This is what I was missing.

I was looking into an issue in Quarkus and I was trying to check for alternatives. I've noticed the `session.delete` with the different parameters and wanted to check if it solves the issue (it doesn't). It also confused me because in reactive we have similar method called `session.remove` that works as `session.delete` but the second parameter is the id.

FYI, the issue we are having on Quarkus, is that `session.remove` or `session.delete` throw an ObjectNotFoundException (or similar) if one tries to remove a row that's not in the db. This approach doesn't fit well with Panache and the `deleteById` method it provides.

**Comment by DavideD** [comment]
So it turns out that `session.delete(String, Object)` actually works as expected when [the second parameter is correct](https://github.com/hibernate/hibernate-test-case-templates/pull/158#issuecomment-1105034081) (Thanks @dreab8)

And the `EntityNotFoundException` comes from the `session.getReference` when the delete tries to create the proxy because it runs a select on the db. Here's a stacktrace as an example:
```
javax.persistence.EntityNotFoundException: No row with the given identifier exists: [org.hibernate.bugs.ORMUnitTestCase$Flour#1]
    at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:118)
    at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
    at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
    at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:950)
    at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:878)
    at org.hibernate.bugs.ORMUnitTestCase.deleteExistingObject(ORMUnitTestCase.java:80)
    ...
```
I find it a bit weird that we are trying to delete an entity and we get an exception because the entity is not in the db.
But I can understand why it works this way.
 
Thanks everybody for helping me wrapping my head around this.

**Pull request closed without merging**
